### ISSUE TITLE
Can't add to HA

### ISSUE THREAD

**Issue by ukd1** [jxlarrea/ha-emfitqs#11]
I'm getting an error when adding via HACS to HA

![image](https://github.com/jxlarrea/ha-emfitqs/assets/44345/526bbb09-f021-4143-aaae-1e4caa6b29d6)

If I try add directly, it says to add via config. If I add via config, it errors like above.

My config is:

```yaml
emfitqs:

sensor:
  - platform: emfitqs
    host: 192.168.86.193 # Replace with your Emfit QS device IP Address.
    scan_interval: 10
    resources:
      - heart_rate
      - respiratory_rate
      - activity_level
      - seconds_in_bed

binary_sensor:
  - platform: emfitqs
    host: 192.168.86.193 # Replace with your Emfit QS device IP Address.
    scan_interval: 10
    monitored_conditions:
      - bed_presence
```

Versions of things:
```
Core: 2024.1.3
Supervisor: 2023.12.1
Operating System: 11.4
Frontend: 20240104.0
```
